import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import React, { useEffect, useState } from 'react';
import Card from '../ui/card';
import { Badge } from '../ui/badge';
import { Table, THead, TBody, TR, TH, TD } from '../ui/table';
import { getRepos } from '../services/api';
import { EmptyState } from '../ui/empty-state';
export default function ReposPage() {
    const [repos, setRepos] = useState([]);
    const [filter, setFilter] = useState('all');
    useEffect(() => {
        getRepos().then((data) => setRepos(data.repos || []));
    }, []);
    const filtered = filter === 'all' ? repos : repos.filter((r) => r.status === filter);
    return (_jsxs("div", { style: { display: 'flex', flexDirection: 'column', gap: 16 }, children: [_jsxs(Card, { title: 'Repositories', subtitle: 'Workflow health & PR activity', children: [_jsx("div", { style: { display: 'flex', gap: 8, marginBottom: 12 }, role: "group", "aria-label": "Repo status filter", children: ['all', 'green', 'yellow', 'red'].map((f) => (_jsxs("button", { "aria-pressed": f === filter, className: 'cursor-pointer', onClick: () => setFilter(f), style: { padding: '4px 10px', border: '1px solid var(--border)', borderRadius: 999, background: f === filter ? 'var(--panel)' : 'transparent' }, children: [f, " (", f === 'all' ? repos.length : repos.filter(r => r.status === f).length, ")"] }, f))) }), _jsxs(Table, { children: [_jsx(THead, { children: _jsxs(TR, { children: [_jsx(TH, { children: "Repository" }), _jsx(TH, { children: "Status" }), _jsx(TH, { children: "Open PRs" }), _jsx(TH, { children: "Workflows" }), _jsx(TH, { children: "Updated" })] }) }), _jsx(TBody, { children: filtered.length === 0 ? (_jsx(TR, { children: _jsx(TD, { colSpan: 5, children: _jsx(EmptyState, { title: 'No repositories', message: 'No repo data yet.' }) }) })) : filtered.map((repo) => (_jsxs(TR, { children: [_jsx(TD, { children: repo.url ? (_jsx("a", { href: repo.url, target: '_blank', rel: 'noreferrer', children: _jsx("strong", { children: repo.name }) })) : (_jsx("strong", { children: repo.name })) }), _jsx(TD, { children: _jsxs(Badge, { variant: repo.status === 'green' ? 'success' : repo.status === 'yellow' ? 'warning' : repo.status === 'red' ? 'danger' : 'outline', children: [repo.status === 'green' ? '🟢' : repo.status === 'yellow' ? '🟡' : repo.status === 'red' ? '🔴' : '⚪', " ", repo.status || 'unknown'] }) }), _jsx(TD, { children: repo.openPRs ?? 0 }), _jsx(TD, { children: repo.workflows ?? 0 }), _jsx(TD, { children: repo.updatedAt || '—' })] }, repo.id))) })] })] }), _jsx(Card, { title: 'Recent pull requests', subtitle: 'Review queue', children: _jsx("div", { style: { display: 'flex', flexDirection: 'column', gap: 10 }, children: ['Add billing webhooks', 'Fix theme token mapping', 'Upgrade workflows'].map((item) => (_jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--border)', paddingBottom: 8 }, children: [_jsxs("div", { children: [_jsx("div", { style: { fontWeight: 600 }, children: item }), _jsx("div", { style: { fontSize: 12, opacity: 0.7 }, children: "wjbetech-dashboard \u2022 awaiting review" })] }), _jsx("button", { className: 'cursor-pointer', "aria-label": `Open PR ${item}`, style: { padding: '6px 10px', border: '1px solid var(--border)', borderRadius: 8, background: 'transparent' }, children: "Open" })] }, item))) }) })] }));
}
//# sourceMappingURL=ReposPage.js.map